### ISSUE TITLE
Susy

### ISSUE THREAD

**Issue by standus** [leafo/scssphp#272]
failed at `$_merge: ($_merge: $_value);

in code:
// Deep Set
// --------
// - Set a value deep in nested maps
@function _susy-deep-set(
  $map,
  $keys-value...
) {
  $_value: nth($keys-value, -1);
  $_keys: _susy-truncate-list($keys-value, length($keys-value) - 1);
  $_length: length($_keys);
  $_return: ();

  @for $i from 1 through $_length {
    $_n: 0 - $i;
    $_level: _susy-truncate-list($_keys, $_length + $_n);
    $_level: _susy-deep-get($map, $_level...);
    $_merge: nth($_keys, $_n);
    $_merge: ($_merge: $_value);
    $_return: if($_level, map-merge($_level, $_merge), $_merge);
    $_value: $_return;
  }

  @return $_return;
}

**Comment by robocoder** [comment]
Can you provide a short test case without external dependencies? It makes writing tests easier.

**Comment by standus** [comment]
Do you mean without Susy?

**Comment by robocoder** [comment]
Nevermind, I see the problem. The parser doesn't expect a variable for the map key.

/cc @okj579

**Comment by standus** [comment]
OK. After you will fix the problem, could you make test compilation with Susy FW please?

**Comment by robocoder** [comment]
I've pushed a fix onto the `map-patch` branch. As you asked, I didn't get any parser errors with Susy. if it looks good to you, I'll merge it into `master`.

**Comment by standus** [comment]
Still have some errors with Susy:
1. one error:
array_merge(): Argument #2 is not an array
C:\xampp\htdocs\coumes\libs\scssphp\Compiler.php:3021
2. namy errors:
Invalid argument supplied for foreach()
C:\xampp\htdocs\coumes\libs\scssphp\Compiler.php:1192
3. error:
expecting list: failed at `}` /susy/susy/language/../output/shared/_inspect.scss on line 16

This is my test main cscc:
@import "susy/susy";

$susy: (
  flow: ltr,
  math: fluid,
  output: float,
  gutter-position: after,
  container: auto,
  container-position: center,
  columns: 12,
  global-box-sizing: border-box,
  debug: (
    image: show
  )
);

@include border-box-sizing;

#page {
  @include container(970px);
  @media screen and (max-width:750px) {
    @include container(100%);
  }
}

#logo img {
  @include span(3 of 12);
  @media screen and (max-width:600px) {
    @include span(4 wider of 12 );
    margin: 0 span(4 of 12);
  }
}

#panel-central {
  @include span(8 of 12);
  @media screen and (max-width:600px) {
    @include span(10 wider of 12 );
    margin: 0 span(1 of 12);
  }
}

#panel-right {
  @include span(4 of 12 last);
  @media screen and (max-width:600px) {
    @include span(10 wider of 12 );
    margin: 0 span(1 of 12);
 }
}

body {
  background-color: red !imnportant;
}

**Comment by robocoder** [comment]
The parser/compiler errors are fixed, but the output isn't yet what we expect.

**Comment by standus** [comment]
Now errors:
1.
Use of undefined constant STDERR - assumed 'STDERR'
\scssphp\Compiler.php:1012
2.
fwrite() expects parameter 1 to be resource, string given
\scssphp\Compiler.php:1012

**Comment by robocoder** [comment]
Try running `bin/pscss main.scss` instead of `bin/pscss <main.scss`.

**Comment by standus** [comment]
I disabled that line and no errors now.
I dont want use scss as cli soo it will be fine to make some condition for cli call and normal php process.
SOmething like:
if (php_sapi_name() == 'cli' ||
    stristr(php_sapi_name() , 'cgi') ||
    defined('STDIN') ||
    getenv('TERM') ||
    (empty($_SERVER['REMOTE_ADDR']) && !isset($_SERVER['HTTP_USER_AGENT']) && count($_SERVER['argv']) > 0)) {
    //command line log
}
else {
    //normal log
}

**Comment by robocoder** [comment]
I've merged this branch into master.  The remaining issues don't appear to be map related, so I'm temporarily reopening this issue until we isolate some smaller test cases and create separate issues for those.

**Comment by standus** [comment]
Compiled css is still total broken as I describet upper.

**Comment by robocoder** [comment]
The `border-box-sizing` mixin requires `@at-root` support. (#193)

**Comment by robocoder** [comment]
TODO: look into why the `container` and `span` mixins are failing

**Comment by standus** [comment]
I updated last version of scssphp, but compiled css is totally pointless.

**Comment by robocoder** [comment]
`susy-support` depends on `call` support. (#302)

**Comment by robocoder** [comment]
susy passes maps to mixins expecting varargs (#346)

**Comment by robocoder** [comment]
`container` mixin is still failing ... incorrectly calculating the background-size in `parse-span`, i.e., converting the list `1 (container: 100%) wide` to the map `(span: 1, container: 100%, spread: wide)`

`span` mixin causes an exception 'Expected @content inside of mixin: failed at `@content; }` susy/sass/susy/language/susy/_span.scss on line 32'; this looks like a nested mixin scope issue.

**Comment by robocoder** [comment]
`_susy-deep-set` uses `nth($list, -1)` (#347)

**Comment by standus** [comment]
Expected @content inside of mixin: failed at `@content; }` /templates/default/scss/susy/susy/language/susy/_span.scss on line 30

**Comment by robocoder** [comment]
The `span` mixin exception is due to nested mixins. #349.

The undefined `float:` property and `margin-right:` differences are due to scoping changes. #348
