### ISSUE TITLE
for loop fails on undefined vars

### ISSUE THREAD

**Issue by joskoomen** [leafo/scssphp#446]
My project need compiles based on theme colors. This means i have to add vars dynamically to override scss vars.

The project uses Foundation sites (6.1) scss. But some loops return undefined var errors:

```
@for $i from 1 through $grid-column-count {
  // Column width
  .#{$-zf-size}-#{$i} {
    @include grid-col-size($i); // this $i is undefined in the compiler
  }

  // Source ordering
  @if $i < $grid-column-count {
    .#{$-zf-size}-#{$push}-#{$i} {
      @include grid-col-pos($i); // this $i is undefined in the compiler
    }

    .#{$-zf-size}-#{$pull}-#{$i} {
      @include grid-col-pos(-$i); // this $i is undefined in the compiler
    }
  }

  // Offsets
  $o: $i - 1;
  .#{$-zf-size}-#{$offset}-#{$o} {
    @include grid-col-off($o);
  }
}
```

I've added comments where the variables are undefined. I've noticed it with a similar situation:

```
// Heading sizes
@each $size, $headers in $header-sizes {
  @include breakpoint($size) {
    @each $header, $font-size in $headers {
      #{$header} {
        font-size : rem-calc($font-size); // this $font-size var is undefined
      }
    }
  }
}
```

So it seems to fail within loops and inside mixin includes

**Comment by FMCorz** [comment]
I have reproduced this error when trying to compile Bootstrap 4 alpha 2.

Exception - Undefined variable $i: line: 15

```
line 3321 of scssphp/src/Compiler.php: Leafo\ScssPhp\Exception\CompilerException thrown
line 2991 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->throwError()
line 1990 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->get()
line 3615 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->reduce()
line 1717 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->applyArguments()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 958 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 1449 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileBlock()
line 1186 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 1644 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildren()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 1741 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 958 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 1449 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileBlock()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 1722 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 1722 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 958 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 1449 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileBlock()
line 1205 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChild()
line 295 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileChildrenNoReturn()
line 194 of scssphp/src/Compiler.php: call to Leafo\ScssPhp\Compiler->compileRoot()
line 14 of /test.php: call to Leafo\ScssPhp\Compiler->compile()
```

**Test case:**

```
@mixin container() {
    #container {
        @content;
    }
}
@mixin make-col-span($size) {
    width: $size;
}

@mixin make-stuff() {
    @include container() {
      @for $i from 1 through 3 {
        .col-#{$i} {
            color: red;
            @include make-col-span($i);
        }
      }
    }
}

div {
    @include make-stuff();
}
```

**Expected:**

```
div #container .col-1 {
  color: red;
  width: 1;
}
div #container .col-2 {
  color: red;
  width: 2;
}
div #container .col-3 {
  color: red;
  width: 3;
}
```

**Comment by robverhoef** [comment]
I see a similar problem with foundation-sites 6.2.3 (compiling bower_components/foundation-sites/assets/foundation.scss):

Parse error: Undefined variable $i: line: 86

**Comment by FMCorz** [comment]
Could someone please review and comment on the following patch?

https://github.com/leafo/scssphp/compare/master...FMCorz:issue-446

It's clearly not ready to be merged, but I just wonder if I'm heading in the right direction, and how I can improve the patch further so that this can be fixed.

In short, I think that the problem only arises when we've got two `@include` leading to resolving the variables of a function call. Because the environments of both `@include` are marked as `mixin` the variable resolution stops.

Ultimately I think that the function resolving the variables should be given an appropriate scope to start with rather than changing the variable resolution, but I need some guidance as to how to do this.

Cheers!

**Comment by Juje** [comment]
@FMCorz your patch works as it should for the issue from #449. 

So as far as I can see it it should be imported into the repository @leafo?

**Comment by robverhoef** [comment]
@FMCorz Unfortunately it doesn't work for compiling foundation-sites 6.2.3. I still see:
Parse error: Undefined variable $i: line: 86

**Comment by FMCorz** [comment]
@Juje I don't think it should be imported as it, the patch need some clean-up. Beside @robverhoef pointed that Foundation doesn't compile so more work is needed.

**Comment by paxperscientiam** [comment]
Has there been any traction WRT this patch?

**Comment by FMCorz** [comment]
Have you guys tried this? #453

**Comment by paxperscientiam** [comment]
HI @FMCorz 

I've required your issue-446 branch but it's hash is "08a458c...". Have you not commited to said branch?

**Comment by FMCorz** [comment]
I'm not sure I am following but that branch was not up-to-date. Most of the remaining work on this library has been done under the repo moodlehq/scssphp. I have updated my pull request #453 to use the latest patch. Could you check now?

**Comment by paxperscientiam** [comment]
@FMCorz ohhhhh. Sorry, somewhere I got confused.

OK, I will ignore issue-446 and try the "nested-mixins" branch of moodlehq/scssphp.

BRB.

**Comment by paxperscientiam** [comment]
Unfortunately, it is still not working for me. I'm getting an error similar to that reported by @robverhoef as I too am using Foundation. scssphp doesn't seem to like iteration variables.

**Comment by darknailblue** [comment]
I'm attempting to compile foundation and running into the same issue. @robocoder Any idea on a quick fix for this?

**Comment by darknailblue** [comment]
I know this is slightly off-topic but @robverhoef @paxperscientiam Just to give you guys a heads up the @includes that AREN'T compiling on foundation are the foundation-grid include and the foundation-flex-classes.  If you @include every component manually you can get around this and have a separate CSS file for grid and flex classes.

**Comment by paxperscientiam** [comment]
Hey @darknailblue,

Thanks for pointing this out, though I also had to comment out "@include foundation-flex-classes" to get a successful transpilation.

Thanks for the suggestion, though, for now, I'm going to stick with using a combination of nodemon, node-sass, and browsersync for development. scssphp is by far the fastest transpiler I've come across, so I this bug can be remedied soon.

**Comment by darknailblue** [comment]
@paxperscientiam I ended up having to do the same.

**Comment by robocoder** [comment]
v0.6.6 has been tagged and released. Can someone provide an updated test case for this issue? Thanks.

**Comment by paxperscientiam** [comment]
Hi @robocoder ,

I'm testing out the latest release of scssphp (with foundation-sites 6.2.3); however, I am still seeing this error manifest as "Parse error: Undefined variable $i".

**Comment by JumpLink** [comment]
I've created a fork of bootstrap 4 Alpha 4 with backward compatibility for older versions of Sass which should working: https://github.com/JumpLinkNetwork/bootstrap-backward

**Comment by garrett-eclipse** [comment]
Having this same issue with foundation and the grid. Commenting so as to follow this thread for any fixes/updates. Thanks

**Comment by Crunky** [comment]
@JumpLink Thanks. I had similar issues with leafo scssphp. Compile work fine with backwards-files but afterwards there are issues in boostrap colums, col-md-3 + col-md-9 e.g. aren´t side by side in a row.

I double checked it.

**Comment by JumpLink** [comment]
@Crunky did you use the latest Version? I use it in productive and it Works fine for me

**Comment by Crunky** [comment]
Yes i updated now to the latest lessphp Version but the issue is still there ... Strange ...

Can you share how you implement it? So i could compare.

Thanks a lot.

**Comment by Crunky** [comment]
Sry sassphp Version ... :)

**Comment by Crunky** [comment]
Hi, i figured it out. If i compare normal boostrap.css und bootstrap-backwards.css some parts are mising.

If i add them manually, it works fine.

![bs4](https://cloud.githubusercontent.com/assets/8134645/19378252/e0cab44e-91eb-11e6-9d1b-d224b6a7185d.JPG)

**Comment by JumpLink** [comment]
@Crunky Okay you are right, I will fix it. Thank You!

For the next time you can create an issue directly on the bootstrap-backward repo

**Comment by paxperscientiam** [comment]
bump

**Comment by ivanjaros** [comment]
Is there any working solution for Foundation(6.3.0)?

**Comment by ivanjaros** [comment]
btw, any guidance on what is causing the issue would be nice. I'd like to look at it but the code is just too big to just dive into.

**Comment by ivanjaros** [comment]
If someone's interested, I'd pay 50€ for fixing this and making foundation 6.3.0 compile with flex grid.

**Comment by GitNey** [comment]
Stumbled across this today while trying to find a work around for compiling SASS without SSH access on WP-Joints theme in WP. Hoping the attention moves this patch closer to completion.

**Comment by paxperscientiam** [comment]
For anyone interested in a temporary solution, here is a project I've put together that leverages node-sass, browser-sync, and some other stuff.

@ivanjaros You say you've moved on; maybe we can swap ideas. Feel free to check out my repo.
https://github.com/paxperscientiam/webdev-proxy-server

YMMV.

**Comment by penguinstampede** [comment]
fwiw I'm running into two issues in Foundation 6.3.1, both dealing with foundation-grid.
in _row.scss, Undefined variable $gutters
`@mixin grid-row-nest($gutters: $grid-column-gutter) {
  @include -zf-each-breakpoint {
    $margin: rem-calc(-zf-get-bp-val($gutters, $-zf-size)) / 2 * -1;

    margin-right: $margin;
    margin-left: $margin;
  }
}`
and in _classes.scss, lots of problems with $i
`  @include -zf-each-breakpoint {
    @for $i from 1 through $grid-column-count {
      // Column width
      .#{$-zf-size}-#{$i} {
        @include grid-col-size($i);
      }
...`
Trying to get a proper failing test case based on this.

**Comment by corbinfraser** [comment]
Any updates on the flex-grid and grid compilation error with Foundation? Came across it today unfortunately. Seems to be affecting lots of Wordpress themes built with Foundation 6.2+ including WP-Joints

**Comment by sekjal** [comment]
Working on this now so I can use Foundation 6.3.1.

Looks like the `for` variable ($i in this case) value isn't getting passed to it's children. 

The issues with $gutters is separate, I think; I was able to fix it by altering the .scss file slightly.  Not ideal, but it got it out of the way so I could work on this.

**Comment by sekjal** [comment]
Further investigation shows that variables were being set properly in the `for` environment, and that the whole structure of the system doesn't pass variables to children, but rather appends the child environment to the parent environment tree.

This led me to Compiler::get(), where environments are popped off the tree until the appropriate one is found.  There is a little bit of extra logic here to essentially "fall out" of the tree under certain conditions, skipping variables at higher levels and going straight to the root environment.  In doing so, $i was never resolved, because it was skipped.

**Solution:**  comment only Compiler.php line 3122 `$nextIsRoot = true;`

This also solves the issue with $gutters, and the whole of Foundation 6.3.1 now compiles, and seems to render the correct CSS when compared to the distribution file (whitespace aside).

I'm sure, however, there are side effects to this change.  I presume the nextIsRoot logic was placed there for a reason.  Perhaps there are situations where a variable is defined at one of those skipped levels of the tree that is also defined at root, and that's the value we really want, but I can't think of an example at the moment.  I would think, though, if you redefine a variable in a narrower scope, then call a mixin or include, it would make sense to use that value, not the root value, for all child scopes... does this jive with SCSS spec?

**Comment by ADoebeling** [comment]
> Solution: comment out Compiler.php line 3122 $nextIsRoot = true;

@sekjal Thanks a lot, this patched the bug in our cms @contao

**Comment by RedLucas** [comment]
Hey, I got a different Foundation error. Foundation 6.4 specifically involving foundation-sites/scss/components/_breadcrumbs.scss and the `$breadcrumbs-item-separator-item-rtl: '\\' !default;` variable. I believe the backslash causes some problems. 

I also get the issues with the -zf-each-breakpoint mixin. I'm just about to investigate it right now because I must have it working today.

**Comment by pi-tavis** [comment]
> I also get the issues with the -zf-each-breakpoint mixin. I'm just about to investigate it right now because I must have it working today.

@RedLucas Do you got a solution for that issue? I am stuck on the same problem.

**Comment by RedLucas** [comment]
I do have it working... though to be honest the way I got it working I'm not sure I remember. I _believe_ I came to the conclusion that it was the foundation-sites' dependency, specifically sassy-lists, that wasn't working properly. As in the function doesn't exist! Importing the whole foundation sass as a whole fixed it I think, though you could probably import those dependencies separately and have it work as well. 

```@import 'foundation-sites/_vendor/sassy-lists/stylesheets/helpers/missing-dependencies';
@import 'foundation-sites/_vendor/sassy-lists/stylesheets/helpers/true';
@import 'foundation-sites/_vendor/sassy-lists/stylesheets/functions/purge';
@import 'foundation-sites/_vendor/sassy-lists/stylesheets/functions/remove';
@import 'foundation-sites/_vendor/sassy-lists/stylesheets/functions/replace';
@import 'foundation-sites/_vendor/sassy-lists/stylesheets/functions/to-list';```

So is this a scssphp issue? I suppose not really... though I'd have loves a little better error handling for missing functions.. I'm not gonna blame someone else for myself not including the dependencies I needed.

**Comment by pi-tavis** [comment]
Thanks for your suggest. It seems my problem was different to yours. I managed to get a successfull compile with these two changes:

- comment out Compiler.php line 3122 `$nextIsRoot = true;` (as mentioned by @sekjal )
- define variable `$str: '';` somewhere in settings.scss

I don't know if this is a 100% scssphp issue.

**Comment by RedLucas** [comment]
Oh, I had to do $nextIsRoot = true; as well. but that defined variable thing is an interesting thing to try it I run into any similar issue. 

I would say that anything compiled in scssphp that is inconsistent with compiling the same thing in libsass (of whatever version it is declared to be at) deserves a look at. I'm sure people expect parity eh?

Regardless scssphp is an awesome piece of software. :)

**Comment by slucas-nwx** [comment]
Is there any status on fixing this?

**Comment by CotswoldPhoto** [comment]
To bump the above question, is this yet fixed?

**Comment by santiagoarizti** [comment]
This is happening to me today with foundation version 6.4.4-rc1 (according to package-lock.json)
and scssphp version v0.7.4 (according to composer.lock)

error is: Undefined variable $i: line: 86

referring to file _classes.scss on line 86 (below the part where it says: // Sizing (percentage) )

**Comment by TehTux** [comment]
Leafo\ScssPhp\Exception\ParserException: parse error: failed at `$breadcrumbs-item-separator-item-rtl: '\\' !default;` ../vendor/zurb/foundation/assets/../scss/components/_breadcrumbs.scss on line 52

leafo/scssphp: 0.7.5
zurb/foundation: 6.4.3

**Comment by santiagoarizti** [comment]
yes, also this happened @TehTux luckily I do not need the breadcrumbs from Foundation so I was able to just comment it out from the build.

I cannot just comment lines in the scssphp library because it is being kept by composer, so
my solution in the mean time to this issue was to temporarily comment the suggested line, compile the foundation.css file, commit the compiled file to my repo, then uncomment the scssphp lines. I have many other simpler scss files that do need more frequent compilation, those have no problems with the current state of the library.

**Comment by DanielRuf** [comment]
For those who want to apply this change, try https://github.com/cweagans/composer-patches

**Comment by kmajzlik** [comment]
I also have problem with loop.

```
$sites: (
  'a': (
    'primary': red,
    'secondary': orange,
  ),
  'b': (
    'primary': blue,
    'secondary': yellow,
  ),
);

@each $site, $colors in $sites {
  html {
    body.site-#{$site} {
      $primary: map_get($colors, 'primary');
      $secondary: map_get($colors, 'secondary');
      @import "bootstrap/scss/reboot";
    }
  }
}
```
ERROR: Undefined index:  
in /var/www/html/vendor/leafo/scssphp/src/Compiler.php:3568
If i use only one site in that array everything goes well.

For me as temporary hotfix (not recommended) i added `@` on that line.
`$file = @$this->sourceNames[$env->block->sourceIndex];`
I know, very dirty, but works on that project now.

**Comment by Cerdic** [comment]
This is now fixed and work as expected in the initial test case
(can be closed @robocoder )
